<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Travel;

/**
 * StepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StepRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByTravelQueryBuilder(Travel $travel)
    {
        return $this->createQueryBuilder('entity')
            ->where('entity.travel = :travel')
            ->setParameter(':travel', $travel)
        ;
    }
}
