<?php

namespace AppBundle\Repository;

/**
 * TravelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TravelRepository extends \Doctrine\ORM\EntityRepository
{
}
