imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

#doctrine:
#    dbal:
#        dbname: "%database_name%_test"

lexik_jwt_authentication:
    private_key_path:   '%kernel.root_dir%/../var/jwt/test/private.pem'
    public_key_path:    '%kernel.root_dir%/../var/jwt/test/public.pem'
    pass_phrase:        'test'
