<?php
/**
 * Created by PhpStorm.
 * User: quentinmachard
 * Date: 09/08/2017
 * Time: 12:14
 */

namespace AppBundle\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

abstract class AbstractStepType extends AbstractType
{
    /**
     * @inheritDoc
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('name', TextType::class, array(
            'label' => 'Nom',
        ));

        $builder->add('dateStart', DateTimeType::class, array(
            'label' => 'Date de début',
        ));

        $builder->add('dateEnd', DateTimeType::class, array(
            'label' => 'Date de fin',
            'required' => false,
        ));

        $builder->add('summary', TextareaType::class, array(
            'label' => 'Description / Notes',
            'required' => false,
        ));

        $builder->add('price', MoneyType::class, array(
            'label' => 'Prix',
            'required' => false,
        ));

        $this->addCustomFields($builder, $options);

        $builder->add('save', SubmitType::class, array('label' => 'Enregistrer'));
    }

    /**
     * @inheritDoc
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }

    public abstract function addCustomFields(FormBuilderInterface $builder, array $options);
}