<?php
/**
 * Created by PhpStorm.
 * User: quentinmachard
 * Date: 09/08/2017
 * Time: 12:14
 */

namespace AppBundle\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

abstract class AbstractStepType extends AbstractType
{
    /**
     * @inheritDoc
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('name', TextType::class, array(
            'label' => 'form.name',
        ));

        $builder->add('dateStart', DateTimeType::class, array(
            'label' => 'form.date_start',
            'placeholder' => array(
                'year' => 'form.date.year', 'month' => 'form.date.month', 'day' => 'form.date.day', 'hour' => 'form.date.hour', 'minute' => 'form.date.minute',
            ),
        ));

        $builder->add('dateEnd', DateTimeType::class, array(
            'label' => 'form.date_end',
            'placeholder' => array(
                'year' => 'form.date.year', 'month' => 'form.date.month', 'day' => 'form.date.day', 'hour' => 'form.date.hour', 'minute' => 'form.date.minute',
            ),
            'required' => false,
        ));

        $builder->add('summary', TextareaType::class, array(
            'label' => 'form.summary',
            'required' => false,
        ));

        $builder->add('price', MoneyType::class, array(
            'label' => 'form.price',
            'required' => false,
        ));

        $this->addCustomFields($builder, $options);

        $builder->add('save', SubmitType::class, array('label' => 'Enregistrer'));
    }

    /**
     * @inheritDoc
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }

    public abstract function addCustomFields(FormBuilderInterface $builder, array $options);
}