#!/usr/bin/env bash

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../../../../bash/common.lib.sh"

print_header "Testing (Fixtures)" "TravelSheets"
retry_run_command "bin/console sy:fi:lo --env=dev --no-debug -vvv --no-interaction"